# Generated by Django 3.2.8 on 2021-10-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Покупатель', 'verbose_name_plural': 'Список покупателей'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='alcohol.Product', verbose_name='Продукты'),
        ),
    ]
