# Generated by Django 3.2.8 on 2021-10-20 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('alcohol', '0003_imagegallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления для пользователей'},
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='volume',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bottlevolume',
            name='name',
            field=models.CharField(max_length=11, verbose_name='Объем тары'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='use_in_slider',
            field=models.BooleanField(default=False, verbose_name='Использовать в слайдере'),
        ),
    ]
