# Generated by Django 3.2.8 on 2021-10-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0005_rename_for_anonimous_user_cart_for_anonymous_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Общая стоимость'),
        ),
    ]
