# Generated by Django 3.2.8 on 2021-10-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0012_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
