# Generated by Django 3.2.8 on 2021-11-05 14:27

from django.db import migrations, models
import utils.uploading


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0017_alter_cartproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='big_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.uploading.upload_function, verbose_name='Большой логотип'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to=utils.uploading.upload_function, verbose_name='Маленький логотип'),
        ),
    ]
