# Generated by Django 3.2.8 on 2021-11-08 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0018_auto_20211105_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bying_type',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alcohol.address', verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='order',
            name='buying_type',
            field=models.CharField(blank=True, choices=[('self', 'Самовывоз из магазина'), ('delivery', 'Доставка')], default='delivery', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('confirmed', 'Заказ подтвержден'), ('in_progress', 'Заказ в обработке'), ('ready', 'Заказ готов'), ('completed', 'Заказ получен'), ('cancelled', 'Заказ отменен')], default='new', max_length=100),
        ),
    ]
