# Generated by Django 3.2.8 on 2021-11-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0019_auto_20211108_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(blank=True, choices=[('self', 'Самовывоз из магазина'), ('delivery', 'Доставка')], default='delivery', max_length=100, null=True, verbose_name='Тип покупки'),
        ),
    ]
