# Generated by Django 3.2.8 on 2021-11-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0020_alter_order_buying_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alcohol.cart', verbose_name='Корзина'),
        ),
    ]
