# Generated by Django 3.2.8 on 2021-11-09 17:22

from django.db import migrations, models
import utils.uploading


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0021_alter_order_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to=utils.uploading.upload_function, verbose_name='Изображение')),
                ('text', models.TextField(verbose_name='Текст')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('active', models.BooleanField(default=True, verbose_name='Показывать на главной')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайдер',
            },
        ),
    ]
