# Generated by Django 3.2.8 on 2021-11-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0023_customer_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(blank=True, choices=[('Самовывоз из магазина', 'Самовывоз из магазина'), ('Доставка', 'Доставка')], default='Доставка', max_length=100, null=True, verbose_name='Тип покупки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый заказ'), ('Подтвержден', 'Заказ подтвержден'), ('В работе', 'Заказ в обработке'), ('Готов', 'Заказ готов'), ('Получен', 'Заказ получен'), ('Отменен', 'Заказ отменен')], default='Новый', max_length=100),
        ),
    ]
