# Generated by Django 3.2.8 on 2021-11-13 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0024_auto_20211114_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='addresses',
            new_name='user_addresses',
        ),
        migrations.AlterField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='alcohol.customer', verbose_name='Покупатель'),
        ),
    ]
