# Generated by Django 3.2.8 on 2021-11-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0025_auto_20211114_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='address',
            name='building',
            field=models.CharField(default=9, max_length=7, verbose_name='Дом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='entrance',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=300, verbose_name='Улица, дом, квартира, подъезд'),
        ),
    ]
