# Generated by Django 3.2.8 on 2021-11-19 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.uploading


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alcohol', '0026_auto_20211114_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to=utils.uploading.upload_function, verbose_name='Фото')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='Baner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('info', models.CharField(max_length=100, verbose_name='Информация')),
                ('image', models.ImageField(upload_to=utils.uploading.upload_function, verbose_name='Изображение')),
                ('link', models.URLField(blank=True, null=True, verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'Банер',
                'verbose_name_plural': 'Банеры',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AddField(
            model_name='customer',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='Согласен с обработкой п.д.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(blank=True, choices=[('Доставка', 'Доставка'), ('Самовывоз из магазина', 'Самовывоз из магазина')], default='Доставка', max_length=100, null=True, verbose_name='Тип покупки'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='alcohol.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Пользователь', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы к товарам',
            },
        ),
    ]
