# Generated by Django 3.2.8 on 2021-11-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0002_auto_20211121_1344'),
        ('alcohol', '0029_auto_20211121_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='features_for_category', to='specs.CategoryFeature', verbose_name='Характеристика категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='features_for_product', to='specs.ProductFeatures', verbose_name='Характеристика товара'),
        ),
    ]
