# Generated by Django 3.2.8 on 2021-11-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0002_auto_20211121_1344'),
        ('alcohol', '0030_auto_20211121_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='features',
        ),
        migrations.AddField(
            model_name='category',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='features_for_category', to='specs.CategoryFeature', verbose_name='Характеристика категории'),
        ),
    ]
